version: "3"
services:
  app:
    image: test
    build:
      context: .
    container_name: sourcefuse_test
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/test
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
    expose:
      - 8080
    ports:
      - 8081:8080
    restart: unless-stopped
    networks:
       - database-network
  db:
    image: postgres
    container_name: db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
         - POSTGRES_PASSWORD=root
         - POSTGRES_USER=postgres
         - POSTGRES_DB=test
    restart: unless-stopped
    networks:
       - database-network
networks:
  database-network:
    driver: bridge
    external: false
volumes:
  postgres-data: